### PR TITLE
updated hunspell with version 1.6.2 

### PR DESCRIPTION
**Pull request by chcg**
from https://github.com/hunspell/hunspell/releases/tag/v1.6.2
used https://github.com/hunspell/hunspell/archive/v1.6.2.zip

temporarily removed /WX in cmake
see https://ci.appveyor.com/project/chcg/dspellcheck/build/1.335

```
"C:\projects\dspellcheck\_build_x86\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\projects\dspellcheck\_build_x86\DSpellCheck.vcxproj" (default target) (4) ->
  C:\projects\dspellcheck\src\HunspellInterface.cpp(309): warning C4996: 'Hunspell::spell': was declared deprecated [C:\projects\dspellcheck\_build_x86\DSpellCheck.vcxproj]
  C:\projects\dspellcheck\src\HunspellInterface.cpp(467): warning C4996: 'Hunspell::suggest': was declared deprecated [C:\projects\dspellcheck\_build_x86\DSpellCheck.vcxproj]
  C:\projects\dspellcheck\src\HunspellInterface.cpp(480): warning C4996: 'Hunspell::free_list': was declared deprecated [C:\projects\dspellcheck\_build_x86\DSpellCheck.vcxproj]
"C:\projects\dspellcheck\_build_x86\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\projects\dspellcheck\_build_x86\DSpellCheck.vcxproj" (default target) (4) ->
(ClCompile target) -> 
  C:\projects\dspellcheck\src\HunspellInterface.cpp(309): error C2220: warning treated as error - no 'object' file generated [C:\projects\dspellcheck\_build_x86\DSpellCheck.vcxproj]
```

, so needs decision on usage of new interface or disable that specific compiler warning.

New interfaces using std:.string:

```
  /* spell(word) - spellcheck word
   * output: false = bad word, true = good word
   *
   * plus output:
   *   info: information bit array, fields:
   *     SPELL_COMPOUND  = a compound word
   *     SPELL_FORBIDDEN = an explicit forbidden word
   *   root: root (stem), when input is a word with affix(es)
   */
  bool spell(const std::string& word, int* info = NULL, std::string* root = NULL);
  H_DEPRECATED int spell(const char* word, int* info = NULL, char** root = NULL);

  /* suggest(suggestions, word) - search suggestions
   * input: pointer to an array of strings pointer and the (bad) word
   *   array of strings pointer (here *slst) may not be initialized
   * output: number of suggestions in string array, and suggestions in
   *   a newly allocated array of strings (*slts will be NULL when number
   *   of suggestion equals 0.)
   */
  std::vector<std::string> suggest(const std::string& word);
  H_DEPRECATED int suggest(char*** slst, const char* word);
```

### CODE REVIEW

**Comment by Predelnik** [comment]
What's the warning? If it's in headers I think it could be fixed with #pragma warning push, pop since Hunspell should be used only in HunspellInterface.cpp.

**Comment by Predelnik** [comment]
Yeah it should be easy enough to use new interface I translate it all to `std::string` in master anyway. I will probably merge and apply appropriate changes by myself a bit later then.
Thanks for PR!

**Comment by chcg** [comment]
Fixed alread the one for:

`  C:\projects\dspellcheck\src\HunspellInterface.cpp(309): warning C4996: 'Hunspell::spell': was declared deprecated [C:\projects\dspellcheck\_build_x86\DSpellCheck.vcxproj]`

, just removed .c_str() before calling spell(). The one for suggest() seems a little bit more complicated.

Further note, new compiler warnings caused by new version:


```
c:\projects\dspellcheck\deps\hunspell\src\hunspell\affentry.hxx(121): warning C4267: 'return': conversion from 'size_t' to 'short', possible loss of data [C:\projects\dspellcheck\_build_x86\deps\Hunspell\hunspell.vcxproj]
c:\projects\dspellcheck\deps\hunspell\src\hunspell\affentry.hxx(202): warning C4267: 'return': conversion from 'size_t' to 'short', possible loss of data [C:\projects\dspellcheck\_build_x86\deps\Hunspell\hunspell.vcxproj]
  affixmgr.cxx
c:\projects\dspellcheck\deps\hunspell\src\hunspell\affentry.hxx(121): warning C4267: 'return': conversion from 'size_t' to 'short', possible loss of data [C:\projects\dspellcheck\_build_x86\deps\Hunspell\hunspell.vcxproj]
c:\projects\dspellcheck\deps\hunspell\src\hunspell\affentry.hxx(202): warning C4267: 'return': conversion from 'size_t' to 'short', possible loss of data [C:\projects\dspellcheck\_build_x86\deps\Hunspell\hunspell.vcxproj]
C:\projects\dspellcheck\deps\Hunspell\src\hunspell\affixmgr.cxx(1422): warning C4267: '=': conversion from 'size_t' to 'short', possible loss of data [C:\projects\dspellcheck\_build_x86\deps\Hunspell\hunspell.vcxproj]
  csutil.cxx
  filemgr.cxx
  hashmgr.cxx
  hunspell.cxx
  hunzip.cxx
C:\projects\dspellcheck\deps\Hunspell\src\hunspell\hunzip.cxx(181): warning C4244: '=': conversion from 'std::streamsize' to 'int', possible loss of data [C:\projects\dspellcheck\_build_x86\deps\Hunspell\hunspell.vcxproj]
```

**Comment by Predelnik** [comment]
Ok so these last warnings I think should be disabled with push/pop. They probably kept sizes like `short` to  preserve binary compatibility or something like that.

With suggestions it's not that hard, I created `HunspellSuggestions` to cleanly remove them. Now it's not needed, so it should be replace `std::vector<std::string>`, its constructor with simple call to `suggest` and `count ()` to `size ()`. I think that's all.

**Comment by chcg** [comment]
See https://github.com/hunspell/hunspell/blob/master/appveyor.yml, hunspell is just build for mingw, so probably this compiler warnings are not visible to them.

Minimal fix also for suggest() added.

I encounter an issue on rightclick to an empty line at:

```
 	DSpellCheck.dll!strlen() Zeile 70	Unbekannt	Symbole wurden geladen.
 	DSpellCheck.dll!std::char_traits<char>::length(const char * const _First) Zeile 481	C++	Symbole wurden geladen.
 	DSpellCheck.dll!std::basic_string_view<char,std::char_traits<char> >::basic_string_view<char,std::char_traits<char> >(const char * const _Ntcts) Zeile 622	C++	Symbole wurden geladen.
>	DSpellCheck.dll!SpellChecker::get_word_at(long char_pos, char * text, long offset) Zeile 839	C++	Symbole wurden geladen.
 	DSpellCheck.dll!SpellChecker::get_word_under_cursor_is_right(long & pos, long & length, bool use_text_cursor) Zeile 806	C++	Symbole wurden geladen.
 	DSpellCheck.dll!SpellChecker::precalculate_menu() Zeile 223	C++	Symbole wurden geladen.
 	DSpellCheck.dll!sub_wnd_proc_notepad(HWND__ * h_wnd, unsigned int message, unsigned __int64 w_param, __int64 l_param) Zeile 132	C++	Symbole wurden geladen.
 	[Externer Code]		Frame mit Anmerkungen
 	SciLexer.dll!00007ffbb71c77a6()	Unbekannt	Es wurden keine Symbole geladen.
 	SciLexer.dll!00007ffbb71cb774()	Unbekannt	Es wurden keine Symbole geladen.
 	[Externer Code]		Frame mit Anmerkungen
 	notepad++.exe!00007ff74a70a25a()	Unbekannt	Es wurden keine Symbole geladen.
 	notepad++.exe!00007ff74a70a3ef()	Unbekannt	Es wurden keine Symbole geladen.
 	[Externer Code]		Frame mit Anmerkungen
 	SciLexer.dll!00007ffbb71a1d2f()	Unbekannt	Es wurden keine Symbole geladen.
 	SciLexer.dll!00007ffbb71c4912()	Unbekannt	Es wurden keine Symbole geladen.
 	SciLexer.dll!00007ffbb71c8386()	Unbekannt	Es wurden keine Symbole geladen.
 	SciLexer.dll!00007ffbb71cb774()	Unbekannt	Es wurden keine Symbole geladen.
 	[Externer Code]		Frame mit Anmerkungen
 	notepad++.exe!00007ff74a70a25a()	Unbekannt	Es wurden keine Symbole geladen.
 	notepad++.exe!00007ff74a70a3ef()	Unbekannt	Es wurden keine Symbole geladen.
 	[Externer Code]		Frame mit Anmerkungen
 	notepad++.exe!00007ff74a73e81e()	Unbekannt	Es wurden keine Symbole geladen.
 	notepad++.exe!00007ff74a74c01c()	Unbekannt	Es wurden keine Symbole geladen.
 	[Externer Code]		Frame mit Anmerkungen
```


```
std::string_view SpellChecker::get_word_at(long char_pos, char* text, long offset) const {
    char* iterator = text + char_pos - offset;

    if (m_current_encoding == EncodingType::utf8) {
        if (utf8_chr(m_delim_utf8_converted.c_str(), iterator))
            iterator = utf8_dec(text, iterator);

        if (iterator == nullptr)
            return nullptr;
```

**Comment by Predelnik** [comment]
Thanks! I will check and merge your PR tomorrow.

**Comment by Predelnik** [comment]
So these warnings about `affentry.hxx` was not in headers included by `hunspell.hxx`? I think they don't matter that much then.

Funny enough Hunspell suggestions now work noticeably slow for me in debug build because Hunspell uses too many `std::string` iterators and `ITERATOR_DEBUG_LEVEL` is enabled. Maybe it will make sense to optionally disable it in CMake in the future.

Thanks for PR!

**Pull request merged**
