### PR TITLE
Fixed memory leak

### PR DESCRIPTION
**Pull request by SinghRajenM**
typos and memory fixed.

### CODE REVIEW

**Comment by SinghRajenM** [comment]
Build failed: it's not me. 😜

**Comment by Predelnik** [comment]
Thank you very much!
Very bad typo indeed. And sorry for x86 build, I've fixed it now, hope it PR will get rechecked automatically.

**Comment by Predelnik** [comment]
Ok I think it needs to be updated to be rechecked, I think I'll just merge it then.

**Comment by SinghRajenM** [comment]
> Very bad typo indeed.

Actually, it is not a typo but copy/paste I feel. Cheers!!!

**Pull request merged**
