### PR TITLE
Fixed npp crash issue

### PR DESCRIPTION
**Pull request by SinghRajenM**
## RCA:
Proxy was set, but used for downloading dictionary.

### Technical details.
At this [line 120](https://github.com/Predelnik/DSpellCheck/blob/master/src/GithubFileListProvider.cpp#L120), [conversion function](https://github.com/Predelnik/DSpellCheck/blob/master/src/utils/WinInet.h#L99) `operator UrlHandle()` is called.

In above converting function `UrlHandle` ctor is called where WIN API `InternetOpenUrl` fails and thrown exception at [Line 25](https://github.com/Predelnik/DSpellCheck/blob/master/src/utils/WinInet.cpp#L25) which is not handled causes notepad++ crash.

### Solution:
Use proxy for downloading dictionary too.

### CODE REVIEW

**Comment by Predelnik** [comment]
Thank you for PR! It would be nice to lower code duplication since the lines you added are essentially copy of lines above, if it's problematic I might merge PR and do it myself later of course.

Also, does it fix #205 entirely? It's a tiny bit confusing since you didn't mention it here.

**Comment by SinghRajenM** [comment]
>Also, does it fix #205 entirely? It's a tiny bit confusing since you didn't mention it here.

Yes, it fixes the issue completely.

>It would be nice to lower code duplication since the lines you added are essentially copy of lines above

I agree, but just to wanted to avoid refactoring. If you want to avoid duplicate, I'll try to refactor.

**Comment by Predelnik** [comment]
Ok @SinghRajenM I think I will merge your PR and fix duplication myself later. I certainly welcome refactoring in my code, so feel free to do it next time :)
Thank you for your contribution!

**Comment by xixidodo** [comment]
NPP v7.8.7 with DSpellCheck 1.4.16 still crash under the scenario in #205

**Pull request merged**
